package output

import (
	"fmt"
	"strings"
	"time"

	"github.com/aadidev/debategpt/internal/debate"
)

// GenerateMarkdown produces the final brainstorm document from the judge's synthesis.
func GenerateMarkdown(question string, judgeOutput string, transcript *debate.Transcript, totalCost float64, judgeMode string, includeTranscript bool) string {
	var sb strings.Builder

	// Header
	sb.WriteString(fmt.Sprintf("# Brainstorm: %s\n\n", question))
	sb.WriteString(fmt.Sprintf("*Generated by DebateGPT on %s | %d agents, %d rounds | Judge: %s | Cost: $%.3f*\n\n",
		time.Now().Format("2006-01-02 15:04"),
		len(transcript.Agents),
		len(transcript.Rounds),
		judgeMode,
		totalCost,
	))
	sb.WriteString("---\n\n")

	// Judge's synthesized output
	sb.WriteString(judgeOutput)
	sb.WriteString("\n\n")

	// Transcript (optional)
	if includeTranscript && transcript != nil {
		sb.WriteString("---\n\n")
		sb.WriteString("<details><summary>📜 Full Debate Transcript</summary>\n\n")
		for _, round := range transcript.Rounds {
			sb.WriteString(fmt.Sprintf("### Round %d: %s\n\n", round.Number, round.Phase))
			for name, entry := range round.Responses {
				sb.WriteString(fmt.Sprintf("#### %s\n\n", name))
				sb.WriteString(entry.Content)
				sb.WriteString(fmt.Sprintf("\n\n*(%d input tokens, %d output tokens, %.1fs)*\n\n",
					entry.TokensIn, entry.TokensOut, entry.Latency.Seconds()))
			}
		}
		sb.WriteString("</details>\n")
	}

	return sb.String()
}
